package com.aerotopo.learning;

import javax.sql.DataSource;
import java.sql.*;
import java.util.*;

public final class JdbcLab {
    private final DataSource source;
    public JdbcLab(DataSource source) { this.source=source; }
    public void initialize() throws SQLException {
        try(Connection connection=source.getConnection(); Statement statement=connection.createStatement()) {
            statement.execute("create table if not exists lab_checkpoint(id bigint generated by default as identity primary key,label varchar(80) not null unique,z double precision not null)");
        }
    }
    public long insert(String label,double z) throws SQLException {
        try(Connection connection=source.getConnection();
            PreparedStatement statement=connection.prepareStatement("insert into lab_checkpoint(label,z) values(?,?)",Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1,label);statement.setDouble(2,z);statement.executeUpdate();
            try(ResultSet keys=statement.getGeneratedKeys()) {
                if(!keys.next()) throw new SQLException("Missing generated key");
                return keys.getLong(1);
            }
        }
    }
    public List<String> above(double elevation) throws SQLException {
        try(Connection connection=source.getConnection();
            PreparedStatement statement=connection.prepareStatement("select label from lab_checkpoint where z > ? order by label",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY)) {
            statement.setQueryTimeout(2);statement.setDouble(1,elevation);
            try(ResultSet rows=statement.executeQuery()) {
                var result=new ArrayList<String>();
                while(rows.next()) result.add(rows.getString("label"));
                if(rows.last()) { rows.beforeFirst(); }
                return result;
            }
        }
    }
    public void batch(Map<String,Double> observations) throws SQLException {
        try(Connection connection=source.getConnection()) {
            boolean auto=connection.getAutoCommit();
            connection.setAutoCommit(false);
            connection.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
            try(PreparedStatement statement=connection.prepareStatement("insert into lab_checkpoint(label,z) values(?,?)")) {
                Savepoint before=connection.setSavepoint("before_batch");
                try {
                    for(var entry:observations.entrySet()) {
                        statement.setString(1,entry.getKey());statement.setDouble(2,entry.getValue());statement.addBatch();
                    }
                    statement.executeBatch();connection.releaseSavepoint(before);connection.commit();
                } catch(SQLException failure) { connection.rollback(before);connection.rollback();throw failure; }
            } finally { connection.setAutoCommit(auto); }
        }
    }
    public Map<String,Object> metadata() throws SQLException {
        try(Connection connection=source.getConnection();Statement statement=connection.createStatement();
            ResultSet rows=statement.executeQuery("select * from lab_checkpoint where 1=0")) {
            DatabaseMetaData database=connection.getMetaData();
            ResultSetMetaData columns=rows.getMetaData();
            return Map.of("database",database.getDatabaseProductName(),"driver",database.getDriverName(),
                    "columns",columns.getColumnCount(),"batch",database.supportsBatchUpdates());
        }
    }
    public int absoluteWithCallable(int value) throws SQLException {
        try(Connection connection=source.getConnection();CallableStatement call=connection.prepareCall("{? = call ABS(?)}")) {
            call.registerOutParameter(1,Types.INTEGER);call.setInt(2,value);call.execute();return call.getInt(1);
        }
    }
}
