apiVersion: apps/v1
kind: Deployment
metadata:
  name: aerotopo
spec:
  replicas: 1
  selector:
    matchLabels: {app: aerotopo}
  template:
    metadata:
      labels: {app: aerotopo}
    spec:
      securityContext: {runAsNonRoot: true, runAsUser: 10001}
      containers:
        - name: app
          image: aerotopo:1.0.0
          ports: [{containerPort: 8080}]
          env:
            - {name: SPRING_PROFILES_ACTIVE, value: postgres}
          envFrom:
            - secretRef: {name: aerotopo-config}
          resources:
            requests: {cpu: 250m, memory: 512Mi}
            limits: {cpu: '1', memory: 1Gi}
          readinessProbe:
            httpGet: {path: /actuator/health, port: 8080}
            initialDelaySeconds: 20
          livenessProbe:
            httpGet: {path: /actuator/health/liveness, port: 8080}
            initialDelaySeconds: 60
          securityContext: {allowPrivilegeEscalation: false}
---
apiVersion: v1
kind: Service
metadata:
  name: aerotopo
spec:
  selector: {app: aerotopo}
  ports: [{port: 8080, targetPort: 8080}]
